### ISSUE TITLE
[Feature]: First Semaphore application 

### ISSUE THREAD

**Issue by Doozers** [PoCInnovation/SismoC#4]
### Description

Inside a directory named `Semaphoc`, create a dApp with a minimalist react interface using [Semaphore Protocol](https://semaphore.appliedzkp.org/docs/introduction).

### Expected behaviour

Your app must be able to:

- [x] Store a Semaphore identity.
- [x] Create signal & proofs that will be verified ON-chain.
- [x] Detect any signal emitted by the contract.

**Comment by leodubosclard** [comment]
*next
